### PR TITLE
L5 Support

### PR DESCRIPTION
**Pull request by trupedia**
Hi Robert,

my first attempt to make it work on L5, works for me on my local machine.

Best

Julian

### CODE REVIEW

**Comment by weotch** [comment]
Thanks for this, gonna make some tweaks on top of it and tag it today.

**Comment by trupedia** [comment]
Cool, thanks.

By the way, I created another library on top of yours:

https://github.com/trupedia/laravel-blade-haml

which extends the Blade Syntax style. Saw it in one of your issues. Hope
you don't mind. If you need another form of Credit/acknowledgement please
let me know.

Best

Julian

2015-04-15 0:05 GMT+02:00 Robert Reinhard <notifications@github.com>:

**Comment by weotch** [comment]
Oh cool.  Nah, you don't need to do anything special.  

But if the two are mutually exclusive, why don't we add your functionality into mine so there is a just one goto HAML adapter for Laravel?

It looks like yours just extends the BladeCompiler ... is that all that was needed to get it working?

**Comment by trupedia** [comment]
Great, sure we can do that. One place is better than two. Maybe we can work
together on that repo then?
Just couldn't wait for the PR to be merged, because I use the package in
production for some small projects ;)

Yes, after some testing, it just was that easy :)

Am Mittwoch, 15. April 2015 schrieb Robert Reinhard :

**Comment by weotch** [comment]
Ok, I've invited you to the team.  You cool adding that other compiler for Blade, then?

**Comment by trupedia** [comment]
Thanks. Yes, for sure. Should I do it or will you? Because if I do it, I
will do it tomorrow. Here in germany it's nearly 2 o'clock in the morning ;)

2015-04-15 1:39 GMT+02:00 Robert Reinhard <notifications@github.com>:

**Comment by weotch** [comment]
Oh damn, ha.  Yeah, I'll throw it up right now.  Go to bed!

**Comment by trupedia** [comment]
Cool, thanks ;)
I'll give it a look tomorrow then.

2015-04-15 1:43 GMT+02:00 Robert Reinhard <notifications@github.com>:

**Comment by trupedia** [comment]
Hi Robert,

found a bug while registering the extension for the Blade syntax. Have a
commit waiting for this, but actually the team role doesn't include the
repo that I can push it to the master branch ;)

Best

Julian

2015-04-15 1:45 GMT+02:00 Julian Karhoff <j.karhoff@trupedia.de>:

**Comment by weotch** [comment]
Ha ok, that's fixed now.

**Comment by trupedia** [comment]
Great, pushed it. I'll check if it's now working properly in L5.

2015-04-15 18:08 GMT+02:00 Robert Reinhard <notifications@github.com>:

**Pull request merged**
